### ISSUE TITLE
Issue after implementing build system lesson06-02

### ISSUE THREAD

**Issue by dmc2015** [victorkane/recipe-js#3]
I am on branch lesson06-02.

I have replicated everything with the exception of a few naming conventions. For some reason when I start the my app it says it can't find 'recipeJSApp'. 

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.4/$injector/modulerr?p0=RecipeJSApp&p1=Erro…tp%3A%2F%2Flocalhost%3A3000%2Fvendor%2Fangular%2Fangular.min.js%3A19%3A381)

Failed to instantiate module RecipeJSApp due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.4.4/$injector/modulerr?p0=u...)
    at Error (native)
    at http://localhost:3000/vendor/angular/angular.min.js:6:416
    at http://localhost:3000/vendor/angular/angular.min.js:38:98
    at m (http://localhost:3000/vendor/angular/angular.min.js:7:322)
    at g (http://localhost:3000/vendor/angular/angular.min.js:37:180)
    at http://localhost:3000/vendor/angular/angular.min.js:37:349
    at m (http://localhost:3000/vendor/angular/angular.min.js:7:322)
    at g (http://localhost:3000/vendor/angular/angular.min.js:37:180)
    at eb (http://localhost:3000/vendor/angular/angular.min.js:40:435)
    at d (http://localhost:3000/vendor/angular/angular.min.js:19:381

to build the environment I use 

```
Command Line
gulp stage
```

on the command line.

then I run the server

```
Command Line
node server.js
```

I am starting my app from "./stage/index.html" and the app's module is initialized on line one. I am not sure why it cannot find my module because they are injected at the bottom of the same file.

Any guidance would be appreciated.
Here is my repo, it is not on the master branch. 

https://github.com/dmc2015/my-recipe-ng/tree/lesson0601-0604

**Comment by victorkane** [comment]
This is not an issue with this repo.
It is an issue with your repo, and should be placed there.

I cloned your repo, and there is a problem with the package.json. I was unable to run `npm install`, upon doing so got the following error:

```
$ git clone https://github.com/dmc2015/my-recipe-ng.git
Cloning into 'my-recipe-ng'...
remote: Counting objects: 666, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 666 (delta 55), reused 0 (delta 0), pack-reused 485
Receiving objects: 100% (666/666), 738.75 KiB | 336.00 KiB/s, done.
Resolving deltas: 100% (195/195), done.
Checking connectivity... done.
Victor-Kanes-MacBook-Pro:dmc2015 victorkane$ ls
my-recipe-ng
Victor-Kanes-MacBook-Pro:dmc2015 victorkane$ cd my-recipe-ng/
Victor-Kanes-MacBook-Pro:my-recipe-ng victorkane$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.2
npm ERR! file /Users/victorkane/tmp/dmc2015/my-recipe-ng/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 79:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Users/victorkane/tmp/dmc2015/my-recipe-ng/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/victorkane/tmp/dmc2015/my-recipe-ng/npm-debug.log
Victor-Kanes-MacBook-Pro:my-recipe-ng victorkane$
```

**Comment by victorkane** [comment]
Closing issue as inappropriate for this repo.
